services:
  apicurio-registry:
    image: apicurio/apicurio-registry:3.1.2
    container_name: apicurio-registry-inmemorywithstudio_api
    environment:
      apicurio.rest.deletion.group.enabled: "true"
      apicurio.rest.deletion.artifact.enabled: "true"
      apicurio.rest.deletion.artifact-version.enabled: "true"
      apicurio.rest.mutability.artifact-version-content.enabled: "true"
      QUARKUS_HTTP_CORS_ORIGINS: "*"
    ports:
      - "8080:8080"

  apicurio-registry-ui:
    image: apicurio/apicurio-registry-ui:3.1.2
    container_name: apicurio-registry-inmemorywithstudio_ui
    ports:
      - "8888:8080"
    depends_on:
      - apicurio-registry
